#!/usr/bin/env python

import pandas as pd
columns=['Date Time',' Water Level']
WL = pd.read_csv('/ufrc/bsc4452/share/Class_Files/data/CO-OPS__8729108__wl.csv', usecols=columns)
WL.loc[WL[' Water Level'].idxmax()]
